language: python

python:
  - "2.7"

services:
  - redis-server

# command to install dependencies
install:
    - pip install -e .
    - pip install -r dev-requirements.txt

# command to run tests
script: py.test
